### ISSUE TITLE
Video of 8 minutes progress bar only partitions for the first 20 seconds

### ISSUE THREAD

**Issue by yan-shcherbakov** [brightcove/videojs-thumbnails#11]
When I have an 8 minute video and thumbnails in 5 second intervals. When you hover over the progress bar, it only covers 20 seconds of the video. So when I hover over the end of the video, it displays the thumbnail at 20 seconds into the video.

**Comment by AlapArslan** [comment]
if the video length is 5 min or 10 min or 1 hour then how can we set the thumbnail interval of 5 sec for different lengths of videos?
