### ISSUE TITLE
Sponsor WebVTT support

### ISSUE THREAD

**Issue by Cervenka** [brightcove/videojs-thumbnails#22]
We'd like to sponsor an additional feature: Scrubbing thumbnails support for WebVTT with spacial fragments for sprites.
JWPlayer currently supports that. (http://support.jwplayer.com/customer/portal/articles/1407439-adding-preview-thumbnails)

If someone is interested please contact me at florian@cervenka.at.

**Comment by dirkjanm** [comment]
For those still interested in this, I've created a fork which works exclusively with WebVTT files and the new metadata track support in video.js:
https://github.com/dirkjanm/videojs-vtt-thumbnails

**Comment by dmlap** [comment]
@dirkjanm that's awesome! I'm going to close this since your plugin solves the issue for anyone who wants thumbnails through WebVTT.

**Comment by dirkjanm** [comment]
So you want to keep this plugin in the current style? I wasn't sure yet if you wanted to pull the code in any way or that I should "release" it as a separate plugin.

**Comment by dmlap** [comment]
@dirkjanm it would be awesome to merge VTT support into this project if you're up for it. Feel like opening a PR?

**Comment by dirkjanm** [comment]
I dont mind making one but you should not that it **only** supports VTT and not the old config style anymore since I found that one way too complicated when trying to use more complicated image setups.

**Comment by dmlap** [comment]
As long as the VTT-based configuration is easy, I'd be up for bumping the major version and dropping support for the old config syntax.

**Comment by dirkjanm** [comment]
It's as easy as adding a metadata track to the video object. I updated the Readme.md as well to reflect the new config style. I'll test some more next week on how it works with WebVTT files which don't have explicitly specified image dimensions and once that works I'll create a PR.

**Comment by dmlap** [comment]
Sounds great!
